name: JFrog POC Scan

on:
  push:
    branches: [ "sit" ]
  workflow_dispatch:

env:
  JF_URL: 'https://trial9cn0pa.jfrog.io'
  RT_REPO: 'dotnet-generic-local'
  BUILD_NAME: 'SIT-simple-web-app'
  XRAY_WATCH: 'firdaus-watches'
  JF_USER: 'firdaus.ghazali@izeno.com'

jobs:
  poc-build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗️ Checkout
        uses: actions/checkout@v4

      - name: ☕ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: ⚙️ Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ env.JF_URL }}
          JF_USER: ${{ secrets.JFROG_USER }}
          JF_PASSWORD: ${{ secrets.JFROG_PASSWORD }}

      - name: 🔍 QUICK SCAN (The POC Part)
        # This scans your project files and dependencies directly
        run: jf scan . --format=table

      - name: 📦 Build and Upload
        run: |
          # 1. Build the app
          dotnet publish SimpleWebApp.csproj -c Release -o ./out
          
          # 2. Upload the 'out' folder to Artifactory
          jf rt upload "out/" "${{ env.RT_REPO }}/${{ env.BUILD_NAME }}/${{ github.run_number }}/"
          
